version: 2
jobs:
  build:
    working_directory: ~/hydropi
    docker:
      - image: hypriot/rpi-node:8.1
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install
