version: 2
jobs:
  build:
    docker:
      - image: node:7.10
    working_directory: ~/hydropi
    steps:
      - checkout
      - restore_cache:
          key: client-deps-{{ .Branch }}-{{ checksum "client/package.json"}}
      - run:
          name: Install node-gyp dependencies (Python, GCC and Make)
          command: apt-get install python make gcc
      - run:
          name: Installing common dependencies
          command: npm install
      - run:
          name: Installing server dependencies
          command: npm run server:dependencies
      - run:
          name: Installing client dependencies
          command: npm run client:dependencies
      - save_cache:
          key: client-deps-{{ .Branch }}-{{ checksum "client/package.json"}}
          paths:
            - "client/node_modules"
      - run:
          name: Running client tests
          command: npm run client:test
      - run:
          name: Running server tests
          command: npm run server:test
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/hydropi

  build_arm:
    docker:
      - image: node:8.10
    working_directory: ~/hydropi
    steps:
      - setup_remote_docker
      # use a primary image that already has Docker (recommended)
      # or install it during a build like here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install node-gyp dependencies (Python, GCC and Make)
          command: apt-get install python make gcc
      - run:
          name : Install Balena CLI
          command: npm install balena-cli -g --production --unsafe-perm
      - run:
          name: Build with Balena
          command: |
            balena login --token $BALENA_API_TOKEN
            HOST=$(echo $DOCKER_HOST | awk -F'tcp://|:[0-9]+' '{print $0=$2}')
            DEBUG=1 balena build --logs --emulated --dockerHost $HOST --dockerPort 2376 --application Hydropi

  deploy:
    docker:
      - image: node:8.10
    working_directory: ~/hydropi
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install node-gyp dependencies (Python, GCC and Make)
          command: apt-get install python make gcc
      - run:
          name: Install Balena CLI
          command: npm install balena-cli -g --production --unsafe-perm
      - run:
          name: Deploy to Balena.io
          command: |
            balena login --token $BALENA_API_TOKEN # Env variable stored in CircleCI
            balena push hydropi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - build_arm
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
