version: 2
jobs:
  build:
    docker:
      - image: node:7.10
    working_directory: ~/hydropi
    steps:
      - checkout
      - restore_cache:
          key: client-deps-{{ .Branch }}-{{ checksum "client/package.json"}}
      - run:
          name: Install node-gyp dependencies (Python, GCC and Make)
          command: apt-get install python make gcc
      - run:
          name: Installing common dependencies
          command: npm install
      - run:
          name: Installing server dependencies
          command: npm run server:dependencies
      - run:
          name: Installing client dependencies
          command: npm run client:dependencies
      - save_cache:
          key: client-deps-{{ .Branch }}-{{ checksum "client/package.json"}}
          paths:
            - "client/node_modules"
      - run:
          name: Running client tests
          command: npm run client:test
      - run:
          name: Running server tests
          command: npm run server:test
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/hydropi
  deploy:
    docker:
      - image: node:8.10
    working_directory: ~/hydropi
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install node-gyp dependencies (Python, GCC and Make)
          command: apt-get install python make gcc
      - run:
          name : Install Balena CLI
          command: npm install balena-cli -g --production --unsafe-perm
      - run:
          name : Deploy to Balena.io
          command: |
            balena login --token $BALENA_API_TOKEN # Env variable stored in CircleCI
            balena push hydropi
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
