version: 2
jobs:
  build:
    docker:
      - image: node:7.10
    working_directory: ~/hydropi
    steps:
      - checkout
      - run:
          name: Installing server dependencies
          command: npm install
      - run:
          name: Installing client dependencies
          command: npm run client:dependencies
      - run:
          name: Running client tests
          command: npm run client:test
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/hydropi
  deploy:
    docker:
      - image: node:7.10
    working_directory: ~/hydropi
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name : Deploy to Resin.io
          command: |
            git remote add resin gh_francois_roseberry@git.resin.io:gh_francois_roseberry/hydropi.git
            git push resin master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
