version: 2
jobs:
  build:
    working_directory: ~/hydropi
    docker:
      - image: node:7.10
    steps:
      - checkout
      - run:
          name: Installing server dependencies
          command: npm install
      - run:
          name: Installing client dependencies
          command: npm run client:dependencies
      - run:
          name: Running client tests
          command: npm run client:test
