version: 2
jobs:
  build:
    working_directory: ~/hydropi
    docker:
      - image: node:7.10
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: npm install
