version: 2
jobs:
  build:
    docker:
      - image: node:7.10
    working_directory: ~/hydropi
    steps:
      - checkout
      - restore_cache:
          key: client-deps-{{ .Branch }}-{{ checksum "client/package.json"}}
      - run:
          name: Install node-gyp dependencies (Python, GCC and Make)
          command: apt-get install python make gcc # build base includes g++ and gcc and Make
      - run:
          name: Installing common dependencies
          command: npm install
      - run:
          name: Installing server dependencies
          command: npm run server:dependencies
      - run:
          name: Installing client dependencies
          command: npm run client:dependencies
      - save_cache:
          key: client-deps-{{ .Branch }}-{{ checksum "client/package.json"}}
          paths:
            - "client/node_modules"
      - run:
          name: Running client tests
          command: npm run client:test
      - run:
          name: Running server tests
          command: npm run server:test
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/hydropi
  deploy:
    docker:
      - image: node:7.10
    working_directory: ~/hydropi
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys:
          fingerprints:
            - "62:99:7c:02:c8:94:3a:c1:1d:30:8f:25:ba:ae:95:8a"
      - run:
          name : Deploy to Balena.io
          command: |
            cat resinkey >> ~/.ssh/known_hosts
            git remote add resin gh_francois_roseberry@git.resin.io:gh_francois_roseberry/hydropi.git
            git push resin master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
