export const AIR_TEMPERATURE_NEW_READING = 'AIR_TEMPERATURE_NEW_READING';
export const WATER_TEMPERATURE_NEW_READING = 'WATER_TEMPERATURE_NEW_READING';
export const HUMIDITY_NEW_READING = 'HUMIDITY_NEW_READING';

export const LIGHTING_NEW_STATE = 'LIGHTING_NEW_STATE';
export const LIGHTING_NEW_MODE = 'LIGHTING_NEW_MODE';
export const VENTILATION_NEW_STATE = 'VENTILATION_NEW_STATE';
export const VENTILATION_NEW_MODE = 'VENTILATION_NEW_MODE';
export const PUMP_NEW_STATE = 'PUMP_NEW_STATE';
export const PUMP_NEW_MODE = 'PUMP_NEW_MODE';

export const SET_WATER_TEMPERATURE_SOCKET = 'SET_WATER_TEMPERATURE_SOCKET';
export const SET_AIR_TEMPERATURE_SOCKET = 'SET_AIR_TEMPERATURE_SOCKET';
export const SET_HUMIDITY_SOCKET = 'SET_HUMIDITY_SOCKET';

export const SET_LIGHTING_SOCKET = 'SET_LIGHTING_SOCKET';
export const SET_VENTILATION_SOCKET = 'SET_VENTILATION_SOCKET';
export const SET_PUMP_SOCKET = 'SET_PUMP_SOCKET';
