export const AIR_TEMPERATURE_NEW_READING = 'AIR_TEMPERATURE_NEW_READING';
export const WATER_TEMPERATURE_NEW_READING = 'WATER_TEMPERATURE_NEW_READING';
export const HUMIDITY_NEW_READING = 'HUMIDITY_NEW_READING';

export const LIGHTING_NEW_STATE = 'LIGHTING_NEW_STATE';
export const VENTILATION_NEW_STATE = 'VENTILATION_NEW_STATE';
export const PUMP_NEW_STATE = 'PUMP_NEW_STATE';
