export const AIR_TEMPERATURE_NEW_READING = 'AIR_TEMPERATURE_NEW_READING';
export const WATER_TEMPERATURE_NEW_READING = 'WATER_TEMPERATURE_NEW_READING';
export const HUMIDITY_NEW_READING = 'HUMIDITY_NEW_READING';
